modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="SophieLicense"
issueTrackerURL="https://github.com/Bentcheesee/BetterTables/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]

modId="sophiesbettertables"
version="2.0.0"
displayName="Sophie's Better Tables"

logoFile= "../logo.png"
authors='''
Bentcheesee
'''
credits='''
Anyone who has provided code, PRs, Issues, or otherwise to the github
'''

description='''
Revamps many many loot tables and recipes within modded Minecraft!
'''

[[dependencies.sophiesbettertables]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.sophiesbettertables]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"